[phases.setup]
nixPkgs = ["chromium", "nodejs_20", "python3"]
aptPkgs = ["build-essential"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node index.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
